<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb3558f3ae5bc6b53da36562367db8d7c
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'GithubAnalyzer\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'GithubAnalyzer\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb3558f3ae5bc6b53da36562367db8d7c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb3558f3ae5bc6b53da36562367db8d7c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb3558f3ae5bc6b53da36562367db8d7c::$classMap;

        }, null, ClassLoader::class);
    }
}
