version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wp-github-analyzer

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  wordpress:
  db:
